Repository PEC-CSS/Graveyard2025, pull requests merged in 2025-03, with the labels that each got.

#66 Solved #61, Plague_of_titan_orbs
  cp/Plague_of_titan_orbs_61.py
Labels: pwoc, graveyard, CP

#72 Solved #62
  cp/The_Cipher_Of_The_Ancients_#62.py
Labels: pwoc, graveyard, CP

#76 Weather Application
  web/.DS_Store
  web/weatherapp/cloudy.png
  web/weatherapp/styles.css
  web/weatherapp/weather.html
  web/weatherapp/weather.js
  web/weatherapp/weather.png
Labels: pwoc, graveyard, Web

#86 Snake Water Gun c++ implementation #75
  misc/Snake Water Gun/Snake_Water_Gun.cpp
Labels: pwoc, graveyard

#88 logistic regression #52
  ml/Implement_logistic_Regression_52/logistic_regression.ipynb
Labels: pwoc, graveyard, ML

#91 Sentiment analysis pipeline
  ml/Sentiment Analysis/README.md
  ml/Sentiment Analysis/Sentiment_Analysis_Pipeline.py
  ml/Sentiment Analysis/test.py
  ml/SentimentAnalysisPipeline/README.md
  ml/SentimentAnalysisPipeline/Sentiment_Analysis_Pipeline.py
Labels: pwoc, graveyard, ML

#97 Create #23 Xor optimization.py
  cp/#23 Xor optimization.py
Labels: pwoc, graveyard, CP

#101 Solved #14
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/.gitignore
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/README.md
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/connectDB.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/controllers/url.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/controllers/user.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/index.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/middlewares/auth.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/models/url.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/models/user.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/package-lock.json
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/package.json
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/routes/staticRoute.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/routes/url.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/routes/user.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/services/auth.js
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/views/home.ejs
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/views/login.ejs
  web/url-shortener(user authentication system implementation using jwt and bcrypt) #14/views/signup.ejs
Labels: pwoc, graveyard, Web

#104 AI agent code optimizer
  ml/CodeOptimizer/.gitignore
  ml/CodeOptimizer/README.md
  ml/CodeOptimizer/data/optimized_code/optimized_user_code.py
  ml/CodeOptimizer/data/user_code.py
  ml/CodeOptimizer/main.py
  ml/CodeOptimizer/requirements.txt
Labels: pwoc, graveyard, ML
