Repository PEC-CSS/Graveyard2025, pull requests merged in 2025-02, with the labels that each got.

#28 todo app
  web/todo_app/app.js
  web/todo_app/index.html
  web/todo_app/style.css
Labels: pwoc, graveyard, Web

#36 Added Plot_the_pattern_#32.py to cp folder and solved issue #32
  cp/Plot_the_pattern_#32.py
Labels: pwoc, graveyard, CP

#40 ISO CODE
  web/ISO Code/app.js
  web/ISO Code/cover.jpg
  web/ISO Code/coverpic.jpg
  web/ISO Code/index.html
  web/ISO Code/style.css
Labels: pwoc, graveyard, Web

#38 #20 I have created 2 Ai agents using crew ai and tools 1 is researcher an…
  .DS_Store
  ml/.DS_Store
  ml/AI_Agent_SVIJ/.gitignore
  ml/AI_Agent_SVIJ/README.md
  ml/AI_Agent_SVIJ/knowledge/user_preference.txt
  ml/AI_Agent_SVIJ/pyproject.toml
  ml/AI_Agent_SVIJ/report.md
  ml/AI_Agent_SVIJ/src/ai_agents/__init__.py
  ml/AI_Agent_SVIJ/src/ai_agents/config/agents.yaml
  ml/AI_Agent_SVIJ/src/ai_agents/config/tasks.yaml
  ml/AI_Agent_SVIJ/src/ai_agents/crew.py
  ml/AI_Agent_SVIJ/src/ai_agents/main.py
  ml/AI_Agent_SVIJ/src/ai_agents/tools/__init__.py
  ml/AI_Agent_SVIJ/src/ai_agents/tools/custom_tool.py
Labels: pwoc, graveyard, ML

#44 K-Nearest Neighbours
  ml/K-Nearest Neighbours/K-Nearest Neighbours.py
  ml/K-Nearest Neighbours/Predict.py
  ml/K-Nearest Neighbours/knn_model_pipeline.pkl
  ml/K-Nearest Neighbours/optimized_knn_pipeline.pkl
Labels: pwoc, graveyard, ML

#42 Secret Code of Xorland
  cp/Secret Code of Xorland
Labels: pwoc, graveyard, CP

#45 extention
  .DS_Store
  misc/extension/content.js
  misc/extension/image.png
  misc/extension/manifest.json
  misc/extension/style.css
Labels: pwoc, graveyard, misc

#50 Robo charge optimization
  cp/RoboChargeOptimization/README.md
  cp/RoboChargeOptimization/RoboChargeOptimization.cpp
Labels: pwoc, graveyard, CP

#51 Create The_Wealthy_Traveller_#16.cpp
  cp/The_Wealthy_Traveller_#16.cpp
Labels: pwoc, graveyard, CP
